fail_fast: true

repos:
-   repo: https://github.com/compilerla/conventional-pre-commit
    rev: v2.4.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]

-   repo: https://github.com/asottile/seed-isort-config
    rev: v2.2.0
    hooks:
    -   id: seed-isort-config
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
        args: [
          --line-length=100,
          --multi-line=3,
          --profile=black
        ]

-   repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
      - id: black
        args: [
          --line-length=100
        ]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.7.0
    hooks:
    -   id: mypy
        additional_dependencies: [tokenize-rt==5.2.0, pandas-stubs==2.1.1.230928, types-click==7.1.8]
        args: [
          --strict,  # Note: try not to remove strict type checking
          --ignore-missing-imports
        ]
        log_file: mypy.log

-   repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
    -   id: flake8
        args: [
          --max-line-length=100
        ]
        log_file: flake8.log

#-   repo: local
#    hooks:
#      - id: pylint
#        name: pylint
#        entry: bash -c 'pylint "$@" || true' --
#        language: system
#        types: [python]
#        log_file: pylint.log
